#:schema node_modules/wrangler/config-schema.json
name = "twikoo"
main = "src/index.js"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"

routes = [
  { pattern = "twikoo.tsxc.xyz", custom_domain = true }
]

[[d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "twikoo"
database_id = "3131b370-3831-4801-8b01-4503c1d2044b"

[[r2_buckets]]
binding = "R2"
bucket_name = "twikoo"

[vars]
R2_PUBLIC_URL = "https://r2.twikoo.tsxc.xyz"

[dev]
port = 5000
